/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/jet-engine.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/jet-engine.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 1.28, 0]} rotation={[0, 0, -Math.PI / 2]}>
        <group position={[0, 0.18, 0]}>
          <group rotation={[0, Math.PI / 10, 0]}>
            <mesh geometry={nodes.fan_blade_1.geometry} material={materials.fan_blade} rotation={[0, 0, 0.42]} />
          </group>
          <group rotation={[0, Math.PI / 5, 0]}>
            <mesh geometry={nodes.fan_blade_2.geometry} material={materials.fan_blade} rotation={[0, 0, 0.42]} />
          </group>
          <group rotation={[0, 0.942, 0]}>
            <mesh geometry={nodes.fan_blade_3.geometry} material={materials.fan_blade} rotation={[0, 0, 0.42]} />
          </group>
          <group rotation={[0, 1.257, 0]}>
            <mesh geometry={nodes.fan_blade_4.geometry} material={materials.fan_blade} rotation={[0, 0, 0.42]} />
          </group>
          <group rotation={[0, Math.PI / 2, 0]}>
            <mesh geometry={nodes.fan_blade_5.geometry} material={materials.fan_blade} rotation={[0, 0, 0.42]} />
          </group>
          <group rotation={[-Math.PI, 1.257, -Math.PI]}>
            <mesh geometry={nodes.fan_blade_6.geometry} material={materials.fan_blade} rotation={[0, 0, 0.42]} />
          </group>
          <group rotation={[-Math.PI, 0.942, -Math.PI]}>
            <mesh geometry={nodes.fan_blade_7.geometry} material={materials.fan_blade} rotation={[0, 0, 0.42]} />
          </group>
          <group rotation={[-Math.PI, Math.PI / 5, -Math.PI]}>
            <mesh geometry={nodes.fan_blade_8.geometry} material={materials.fan_blade} rotation={[0, 0, 0.42]} />
          </group>
          <group rotation={[-Math.PI, Math.PI / 10, -Math.PI]}>
            <mesh geometry={nodes.fan_blade_9.geometry} material={materials.fan_blade} rotation={[0, 0, 0.42]} />
          </group>
          <group rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh geometry={nodes.fan_blade_10.geometry} material={materials.fan_blade} rotation={[0, 0, 0.42]} />
          </group>
          <group rotation={[-Math.PI, -Math.PI / 10, -Math.PI]}>
            <mesh geometry={nodes.fan_blade_11.geometry} material={materials.fan_blade} rotation={[0, 0, 0.42]} />
          </group>
          <group rotation={[-Math.PI, -Math.PI / 5, -Math.PI]}>
            <mesh geometry={nodes.fan_blade_12.geometry} material={materials.fan_blade} rotation={[0, 0, 0.42]} />
          </group>
          <group rotation={[-Math.PI, -0.942, -Math.PI]}>
            <mesh geometry={nodes.fan_blade_13.geometry} material={materials.fan_blade} rotation={[0, 0, 0.42]} />
          </group>
          <group rotation={[Math.PI, -1.257, Math.PI]}>
            <mesh geometry={nodes.fan_blade_14.geometry} material={materials.fan_blade} rotation={[0, 0, 0.42]} />
          </group>
          <group rotation={[0, -Math.PI / 2, 0]}>
            <mesh geometry={nodes.fan_blade_15.geometry} material={materials.fan_blade} rotation={[0, 0, 0.42]} />
          </group>
          <group rotation={[0, -1.257, 0]}>
            <mesh geometry={nodes.fan_blade_16.geometry} material={materials.fan_blade} rotation={[0, 0, 0.42]} />
          </group>
          <group rotation={[0, -0.942, 0]}>
            <mesh geometry={nodes.fan_blade_17.geometry} material={materials.fan_blade} rotation={[0, 0, 0.42]} />
          </group>
          <group rotation={[0, -Math.PI / 5, 0]}>
            <mesh geometry={nodes.fan_blade_18.geometry} material={materials.fan_blade} rotation={[0, 0, 0.42]} />
          </group>
          <group rotation={[0, -Math.PI / 10, 0]}>
            <mesh geometry={nodes.fan_blade_19.geometry} material={materials.fan_blade} rotation={[0, 0, 0.42]} />
          </group>
          <mesh geometry={nodes.fan_blade_0.geometry} material={materials.fan_blade} rotation={[0, 0, 0.42]} />
        </group>
        <group position={[0, 2.05, 0]}>
          <mesh geometry={nodes.strut_fairing_0.geometry} material={materials.cowl_gray} rotation={[Math.PI / 2, 0, 0]} />
        </group>
        <group position={[0, 2.05, 0]} rotation={[0, Math.PI / 2, 0]}>
          <mesh geometry={nodes.strut_fairing_1.geometry} material={materials.cowl_gray} rotation={[Math.PI / 2, 0, 0]} />
        </group>
        <group position={[0, 2.05, 0]} rotation={[-Math.PI, 0, -Math.PI]}>
          <mesh geometry={nodes.strut_fairing_2.geometry} material={materials.cowl_gray} rotation={[Math.PI / 2, 0, 0]} />
        </group>
        <group position={[0, 2.05, 0]} rotation={[0, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.mounting_pylon.geometry} material={materials.cowl_gray} rotation={[Math.PI / 2, 0, 0]} />
        </group>
        <mesh geometry={nodes.nacelle.geometry} material={materials.nacelle_white} />
        <mesh geometry={nodes.inlet_lip.geometry} material={materials.nacelle_white} position={[0, 0.04, 0]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.core_cowling.geometry} material={materials.cowl_gray} />
        <mesh geometry={nodes.nozzle_cap.geometry} material={materials.hub_dark} position={[0, 3.6, 0]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.fan_spinner.geometry} material={materials.hub_dark} position={[0, 0.06, 0]} rotation={[0, 0, Math.PI]} />
      </group>
      <mesh geometry={nodes.trestle_front_collar.geometry} material={materials.stand_steel} position={[0.7, 1.28, 0]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.trestle_front_leg_0.geometry} material={materials.stand_steel} position={[0.7, 0.182, -0.15]} />
      <mesh geometry={nodes.trestle_front_leg_1.geometry} material={materials.stand_steel} position={[0.7, 0.182, 0.15]} />
      <mesh geometry={nodes.trestle_front_base.geometry} material={materials.stand_steel} position={[0.7, 0.015, 0]} />
      <mesh geometry={nodes.trestle_rear_collar.geometry} material={materials.stand_steel} position={[2.2, 1.28, 0]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.trestle_rear_leg_0.geometry} material={materials.stand_steel} position={[2.2, 0.23, -0.15]} />
      <mesh geometry={nodes.trestle_rear_leg_1.geometry} material={materials.stand_steel} position={[2.2, 0.23, 0.15]} />
      <mesh geometry={nodes.trestle_rear_base.geometry} material={materials.stand_steel} position={[2.2, 0.015, 0]} />
    </group>
  )
}

useGLTF.preload('/jet-engine.glb')
