/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/rolling-bearing.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/rolling-bearing.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[0.15, 0, 0]}>
        <group rotation={[0, -0.193, 0]}>
          <mesh geometry={nodes.roller_0_0.geometry} material={materials.roller_chrome} position={[0.63, -0.14, 0]} />
          <mesh geometry={nodes.roller_0_1.geometry} material={materials.roller_chrome} position={[0.582, -0.14, 0.241]} />
          <mesh geometry={nodes.roller_0_2.geometry} material={materials.roller_chrome} position={[0.445, -0.14, 0.445]} />
          <mesh geometry={nodes.roller_0_3.geometry} material={materials.roller_chrome} position={[0.241, -0.14, 0.582]} />
          <mesh geometry={nodes.roller_0_4.geometry} material={materials.roller_chrome} position={[0, -0.14, 0.63]} />
          <mesh geometry={nodes.roller_0_5.geometry} material={materials.roller_chrome} position={[-0.241, -0.14, 0.582]} />
          <mesh geometry={nodes.roller_0_6.geometry} material={materials.roller_chrome} position={[-0.445, -0.14, 0.445]} />
          <mesh geometry={nodes.roller_0_7.geometry} material={materials.roller_chrome} position={[-0.582, -0.14, 0.241]} />
          <mesh geometry={nodes.roller_0_8.geometry} material={materials.roller_chrome} position={[-0.63, -0.14, 0]} />
          <mesh geometry={nodes.roller_0_9.geometry} material={materials.roller_chrome} position={[-0.582, -0.14, -0.241]} />
          <mesh geometry={nodes.roller_0_10.geometry} material={materials.roller_chrome} position={[-0.445, -0.14, -0.445]} />
          <mesh geometry={nodes.roller_0_11.geometry} material={materials.roller_chrome} position={[-0.241, -0.14, -0.582]} />
          <mesh geometry={nodes.roller_0_12.geometry} material={materials.roller_chrome} position={[0, -0.14, -0.63]} />
          <mesh geometry={nodes.roller_0_13.geometry} material={materials.roller_chrome} position={[0.241, -0.14, -0.582]} />
          <mesh geometry={nodes.roller_0_14.geometry} material={materials.roller_chrome} position={[0.445, -0.14, -0.445]} />
          <mesh geometry={nodes.roller_0_15.geometry} material={materials.roller_chrome} position={[0.582, -0.14, -0.241]} />
          <mesh geometry={nodes.roller_1_0.geometry} material={materials.roller_chrome} position={[0.63, 0.14, 0]} />
          <mesh geometry={nodes.roller_1_1.geometry} material={materials.roller_chrome} position={[0.582, 0.14, 0.241]} />
          <mesh geometry={nodes.roller_1_2.geometry} material={materials.roller_chrome} position={[0.445, 0.14, 0.445]} />
          <mesh geometry={nodes.roller_1_3.geometry} material={materials.roller_chrome} position={[0.241, 0.14, 0.582]} />
          <mesh geometry={nodes.roller_1_4.geometry} material={materials.roller_chrome} position={[0, 0.14, 0.63]} />
          <mesh geometry={nodes.roller_1_5.geometry} material={materials.roller_chrome} position={[-0.241, 0.14, 0.582]} />
          <mesh geometry={nodes.roller_1_6.geometry} material={materials.roller_chrome} position={[-0.445, 0.14, 0.445]} />
          <mesh geometry={nodes.roller_1_7.geometry} material={materials.roller_chrome} position={[-0.582, 0.14, 0.241]} />
          <mesh geometry={nodes.roller_1_8.geometry} material={materials.roller_chrome} position={[-0.63, 0.14, 0]} />
          <mesh geometry={nodes.roller_1_9.geometry} material={materials.roller_chrome} position={[-0.582, 0.14, -0.241]} />
          <mesh geometry={nodes.roller_1_10.geometry} material={materials.roller_chrome} position={[-0.445, 0.14, -0.445]} />
          <mesh geometry={nodes.roller_1_11.geometry} material={materials.roller_chrome} position={[-0.241, 0.14, -0.582]} />
          <mesh geometry={nodes.roller_1_12.geometry} material={materials.roller_chrome} position={[0, 0.14, -0.63]} />
          <mesh geometry={nodes.roller_1_13.geometry} material={materials.roller_chrome} position={[0.241, 0.14, -0.582]} />
          <mesh geometry={nodes.roller_1_14.geometry} material={materials.roller_chrome} position={[0.445, 0.14, -0.445]} />
          <mesh geometry={nodes.roller_1_15.geometry} material={materials.roller_chrome} position={[0.582, 0.14, -0.241]} />
        </group>
        <group rotation={[0, -0.193, 0]}>
          <mesh geometry={nodes.cage_rim_0.geometry} material={materials.cage_bronze} position={[0, -0.32, 0]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.cage_rim_1.geometry} material={materials.cage_bronze} position={[0, 0.32, 0]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.cage_bar_0.geometry} material={materials.cage_bronze} position={[0.63, 0, 0]} />
          <mesh geometry={nodes.cage_bar_1.geometry} material={materials.cage_bronze} position={[0.582, 0, 0.241]} />
          <mesh geometry={nodes.cage_bar_2.geometry} material={materials.cage_bronze} position={[0.445, 0, 0.445]} />
          <mesh geometry={nodes.cage_bar_3.geometry} material={materials.cage_bronze} position={[0.241, 0, 0.582]} />
          <mesh geometry={nodes.cage_bar_4.geometry} material={materials.cage_bronze} position={[0, 0, 0.63]} />
          <mesh geometry={nodes.cage_bar_5.geometry} material={materials.cage_bronze} position={[-0.241, 0, 0.582]} />
          <mesh geometry={nodes.cage_bar_6.geometry} material={materials.cage_bronze} position={[-0.445, 0, 0.445]} />
          <mesh geometry={nodes.cage_bar_7.geometry} material={materials.cage_bronze} position={[-0.582, 0, 0.241]} />
          <mesh geometry={nodes.cage_bar_8.geometry} material={materials.cage_bronze} position={[-0.63, 0, 0]} />
          <mesh geometry={nodes.cage_bar_9.geometry} material={materials.cage_bronze} position={[-0.582, 0, -0.241]} />
          <mesh geometry={nodes.cage_bar_10.geometry} material={materials.cage_bronze} position={[-0.445, 0, -0.445]} />
          <mesh geometry={nodes.cage_bar_11.geometry} material={materials.cage_bronze} position={[-0.241, 0, -0.582]} />
          <mesh geometry={nodes.cage_bar_12.geometry} material={materials.cage_bronze} position={[0, 0, -0.63]} />
          <mesh geometry={nodes.cage_bar_13.geometry} material={materials.cage_bronze} position={[0.241, 0, -0.582]} />
          <mesh geometry={nodes.cage_bar_14.geometry} material={materials.cage_bronze} position={[0.445, 0, -0.445]} />
          <mesh geometry={nodes.cage_bar_15.geometry} material={materials.cage_bronze} position={[0.582, 0, -0.241]} />
        </group>
        <group rotation={[0, -0.483, 0]}>
          <mesh geometry={nodes.inner_race.geometry} material={materials.race_steel} />
          <mesh geometry={nodes.shaft.geometry} material={materials.shaft_steel} />
        </group>
        <mesh geometry={nodes.outer_race.geometry} material={materials.race_steel} />
        <mesh geometry={nodes.housing_block.geometry} material={materials.housing_iron} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.load_arrow_shaft.geometry} material={materials.load_arrow} position={[0, 1.715, 0]} />
        <mesh geometry={nodes.load_arrow_head.geometry} material={materials.load_arrow} position={[0, 1.31, 0]} rotation={[Math.PI, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/rolling-bearing.glb')
